name: Barely By Ivy
favicon: null
layout_spectrum: 1
typography_spectrum: 0.93732
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1e1d'
    - '#dfdede'
    - '#504f4e'
    - '#b6b5ad'
    - '#777377'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5445697633549571
purpose: []
