name: Barely By Ivy
favicon: null
layout_spectrum: 0.5976918181404471
typography_spectrum: 0.93732
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1d4cb'
    - '#87b1aa'
    - '#010101'
    - '#ad7166'
    - '#34664b'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5445697633549571
purpose: []
